name: Example Action with Email

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 23f2003092@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: Another step
        run: echo "This is another step!"

